export const CUSTOMER_LIST_VIEW_MODE_STORAGE_KEY = 'wk_customer_list_view_mode'
export const CUSTOMER_LIST_PAGE_QUERY_KEY = 'pageCustomer'
export const CUSTOMER_DETAIL_LIST_PAGE_QUERY_KEY = 'pageCustomerList'
export const CUSTOMER_ROUTE_ACTION_QUERY_KEY = 'actionCustomer'
export const CUSTOMER_ROUTE_ACTION_CREATE = 'createCustomer'
