export const wkIconNames = [
  'ai',
  'stage',
  'profile',
  'customer',
  'crm',
  'event',
  'add',
  'task',
  'knowledge',
  'knowledge-1',
  'contract',
  'set',
  'import',
  'export',
  'fold',
  'new-chat',
  'add-1',
  'application',
  'voice',
  'send',
  'task-1',
  'copy',
  'file',
  'search',
] as const

export type WkIconName = (typeof wkIconNames)[number]

export const wkIconClassMap = {
  ai: 'AI',
  stage: 'stage',
  profile: 'profile',
  customer: 'customer',
  crm: 'crm',
  event: 'event',
  add: 'add',
  task: 'task',
  knowledge: 'knowledge',
  'knowledge-1': 'knowledge-1',
  contract: 'contract',
  set: 'set',
  import: 'import',
  export: 'export',
  fold: 'fold',
  'new-chat': 'new-chat',
  'add-1': 'add-1',
  'application': 'application',
  'voice': 'voice',
  'send': 'send',
  'task-1': 'task-1',
  'copy': 'copy',
  'file': 'file',
  'search': 'search',
} as const satisfies Record<WkIconName, string>
