export const wkIconNames = [
  'ai',
  'stage',
  'profile',
  'customer',
  'crm',
  'meetingRecord',
  'add',
  'task',
  'knowledge',
  'knowledge-1',
  'contract',
  'settings',
  'import',
  'export',
  'fold',
  'new-chat',
  'add-1',
  'application',
] as const

export type WkIconName = (typeof wkIconNames)[number]

export const wkIconClassMap = {
  ai: 'AI',
  stage: 'stage',
  profile: 'profile',
  customer: 'customer',
  'crm': 'crm',
  meetingRecord: 'meeting-record',
  add: 'add',
  task: 'task',
  knowledge: 'knowledge',
  'knowledge-1': 'knowledge-1',
  contract: 'contract',
  settings: 'settings',
  import: 'import',
  export: 'export',
  fold: 'fold',
  'new-chat': 'new-chat',
  'add-1': 'add-1',
  'application': 'application',
} as const satisfies Record<WkIconName, string>
